extends Node

enum CARD_TYPE {
	DOOR,
	TREASURE
}

enum PILE_TYPE {
	DOOR,
	TREASURE,
	DISCARD_DOOR,
	DISCARD_TREASURE,
	TABLE,
	TABLE_PLAYER_1,
	TABLE_PLAYER_2,
	TABLE_PLAYER_3,
	TABLE_PLAYER_4,
	TABLE_PLAYER_5,
	TABLE_PLAYER_6,
	PLAYER_HAND_1,
	PLAYER_HAND_2,
	PLAYER_HAND_3,
	PLAYER_HAND_4,
	PLAYER_HAND_5,
	PLAYER_HAND_6
}

const PILE_TABLE_PLAYER = [
	PILE_TYPE.TABLE_PLAYER_1,
	PILE_TYPE.TABLE_PLAYER_2,
	PILE_TYPE.TABLE_PLAYER_3,
	PILE_TYPE.TABLE_PLAYER_4,
	PILE_TYPE.TABLE_PLAYER_5,
	PILE_TYPE.TABLE_PLAYER_6
]

const PILE_ALL_TABLES = [
	PILE_TYPE.TABLE,
	PILE_TYPE.TABLE_PLAYER_1,
	PILE_TYPE.TABLE_PLAYER_2,
	PILE_TYPE.TABLE_PLAYER_3,
	PILE_TYPE.TABLE_PLAYER_4,
	PILE_TYPE.TABLE_PLAYER_5,
	PILE_TYPE.TABLE_PLAYER_6
]

const PILE_HAND_PLAYER = [
	PILE_TYPE.PLAYER_HAND_1,
	PILE_TYPE.PLAYER_HAND_2,
	PILE_TYPE.PLAYER_HAND_3,
	PILE_TYPE.PLAYER_HAND_4,
	PILE_TYPE.PLAYER_HAND_5,
	PILE_TYPE.PLAYER_HAND_6
]
